# Response ok, but exception is thrown
GET {{BASE_URL}}/api/example/other
Accept: */*
Authorization: Bearer {{webSessionToken}}

###

# No response
POST {{BASE_URL}}/api/example/no-answer
Accept: */*
Authorization: Bearer {{webSessionToken}}
Content-Type: application/json

###

